title: Shalini Maiti # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Vision and Intelligence Student 
  <br><br>
  Generally curious about everything human
  <br><br>
  <a href="https://www.linkedin.com/in/shalini-maiti-a76a2b86/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
